// Jalankan fungsi ini dari menu Run (Jalankan) di atas untuk memasukkan 81 data lama
function migrateOldSponsorData() {
  const ss = Utils.getSpreadsheet();
  const sheet = ss.getSheetByName('Sponsor');
  if (!sheet) {
    Logger.log("Sheet Sponsor belum ada! Jalankan setupDatabase() dulu.");
    return;
  }
  
  // Cek jika sudah ada datanya agar tidak tertumpuk dua kali
  if (sheet.getLastRow() > 1) {
    Logger.log("Sheet sudah berisi data. Hapus baris data lama dulu jika ingin reset ulang.");
    return;
  }
  
  const seedData = [
  [
    "SPN-001",
    "Kurnia Sirup",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Butuh Diskusi dengan Panitia",
    "Perlu didiskusikan terlebih dahulu dengan panitia.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-002",
    "Kopi Tubruk Gajah",
    "-",
    "-",
    "-",
    "Selasa, 11 Agustus 2026",
    "-",
    "Butuh Diskusi dengan Panitia",
    "Perlu didiskusikan terlebih dahulu dengan panitia.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-003",
    "Nutrisari",
    "-",
    "https://www.nutrifood.co.id/collaboration/",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-004",
    "Glow & Lovely",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-005",
    "Kahf Pusat",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditolak",
    "Pengajuan kerja sama ditolak oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-006",
    "Yakult",
    "-",
    "-",
    "murjoko@yakult.co.id",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-007",
    "Smartfren",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-008",
    "Teh Botol Sosro",
    "-",
    "-",
    "contactus@sosro.com",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-009",
    "Good Day",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-010",
    "Ultra Milk",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-011",
    "Wardah",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-012",
    "Emina",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-013",
    "Fruit Tea",
    "-",
    "-",
    "contactus@sosro.com",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-014",
    "Bank Jago",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-015",
    "Miss Glam",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-016",
    "McDonald's",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-017",
    "Pizza Hut",
    "-",
    "csc@phd.co.id/customerservice@pizzahut.co.id",
    "csc@phd.co.id/customerservice@pizzahut.co.id",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-018",
    "Burger Bangor",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-019",
    "Frestea",
    "-",
    "-",
    "ncc@ccep.com",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-020",
    "Ayam Gepuk Pak Gembus",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-021",
    "Mediatama Web",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-022",
    "Talago Sport",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditolak",
    "Pengajuan kerja sama ditolak oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-023",
    "Sunsilk",
    "-",
    "-",
    "Suara.konsumen@Unilever.com",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-024",
    "Dan+Dan",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-025",
    "Le Minerale",
    "-",
    "sofian.halim@mayora.co.id / herry.suwito@mayora.co.id",
    "sofian.halim@mayora.co.id / herry.suwito@mayora.co.id",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-026",
    "Frisian Flag",
    "-",
    "https://forms.office.com/e/mLFse8ZdRT",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-027",
    "Cheetos",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditolak",
    "Pengajuan kerja sama ditolak oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-028",
    "Hydro Coco",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-029",
    "Camille Beauty",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-030",
    "Bingxue",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-031",
    "Mie Sedaap",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-032",
    "Grab",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-033",
    "Pertamina Sumbagut",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Tidak Ada Respons",
    "Sponsor belum memberikan respons setelah dihubungi atau di-follow up.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-034",
    "Cleo",
    "-",
    "https://forms.gle/NXu81NsunCGs5egWA",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-035",
    "Indosat Ooredoo",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-036",
    "AZKO",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-037",
    "Koyuki Padang",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditolak",
    "Pengajuan kerja sama ditolak oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-038",
    "By.U",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-039",
    "SilverQueen",
    "-",
    "-",
    "mikhaela.bunawan@ceres-pt.com",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-040",
    "Azzwars Parfume Pondok",
    "-",
    "-",
    "-",
    "Selasa, 11 Agustus 2026",
    "-",
    "Butuh Diskusi dengan Panitia",
    "Perlu didiskusikan terlebih dahulu dengan panitia.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-041",
    "Ayeah",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-042",
    "Sabena Motor",
    "-",
    "-",
    "-",
    "Selasa, 11 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-043",
    "BSI",
    "-",
    "-",
    "-",
    "Selasa, 11 Agustus 2026",
    "Pertengahan September balik ke BSI UPI",
    "Sudah ke Lokasi",
    "Panitia sudah datang atau bertemu langsung dengan pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-044",
    "Prodia Lab",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-045",
    "PT Semen Padang",
    "-",
    "-",
    "-",
    "Rabu, 12 Agustus 2026",
    "Kamis, 27 Agustus",
    "Deal / Potensial",
    "Sponsor berpotensi bekerja sama atau sudah menyatakan kesediaan.",
    "Antarkan berkas yang di minta",
    "System (Imported)"
  ],
  [
    "SPN-046",
    "Kabbau Apparel",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "akan dihubungi, dan bisa di follow up dalam sehari setelah pengantaran proposal",
    "System (Imported)"
  ],
  [
    "SPN-047",
    "Telkomsel",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Butuh Diskusi dengan Panitia",
    "Perlu didiskusikan terlebih dahulu dengan panitia.",
    "Diskusikan panitia",
    "System (Imported)"
  ],
  [
    "SPN-048",
    "Pegadaian",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "Sponsor belum dihubungi.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-049",
    "Yamaha",
    "-",
    "-",
    "-",
    "Selasa, 11 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-050",
    "Azzwars Parfume Lubeg",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-051",
    "Kopi Kenangan",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-052",
    "Kopi Oz",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "Sponsor belum dihubungi.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-053",
    "PELINDO",
    "-",
    "-",
    "-",
    "Kamis, 20 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-054",
    "Toko Kopi Gara",
    "-",
    "-",
    "-",
    "Rabu, 12 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "Menunggu manajer ke padang, nanti akan diskusi dengan kepanitiaan",
    "System (Imported)"
  ],
  [
    "SPN-055",
    "Bank Mandiri KC Padang Iman Bonjol",
    "-",
    "-",
    "-",
    "Rabu, 12 Agustus 2026",
    "-",
    "Ditolak",
    "Pengajuan kerja sama ditolak oleh pihak sponsor.",
    "Tidak ada follow up dalam 6 hari kerja",
    "System (Imported)"
  ],
  [
    "SPN-056",
    "G-Sport Center",
    "-",
    "-",
    "-",
    "Rabu, 12 Agustus 2026",
    "-",
    "Deal / Potensial",
    "Sponsor berpotensi bekerja sama atau sudah menyatakan kesediaan.",
    "Dapat Voucher dari Gsport",
    "System (Imported)"
  ],
  [
    "SPN-057",
    "tangan kita",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "Sponsor belum dihubungi.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-058",
    "jotun",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "Sponsor belum dihubungi.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-059",
    "aquviva",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Sudah Dihubungi",
    "Sponsor sudah dihubungi, menunggu respons.",
    "tunggu balasan email 1 minggu, kalo tidak ada brrti ditolak",
    "System (Imported)"
  ],
  [
    "SPN-060",
    "BNI",
    "-",
    "-",
    "-",
    "Selasa, 18 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-061",
    "BANK NAGARI",
    "-",
    "-",
    "-",
    "Selasa, 18 Agustus 2026",
    "-",
    "Sudah ke Lokasi",
    "Panitia sudah datang atau bertemu langsung dengan pihak sponsor.",
    "Lampirkan Rekening Bank Nagari, dan foto kopi ktp, dan lampirkan SK acara",
    "System (Imported)"
  ],
  [
    "SPN-062",
    "BigBang Percetakan",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Butuh Diskusi dengan Panitia",
    "Perlu didiskusikan terlebih dahulu dengan panitia.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-063",
    "Mormo Percetakan",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Butuh Diskusi dengan Panitia",
    "Perlu didiskusikan terlebih dahulu dengan panitia.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-064",
    "BTN",
    "-",
    "-",
    "-",
    "Selasa, 18 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-065",
    "PT Pertamina Patra Niaga",
    "-",
    "-",
    "-",
    "Rabu, 19 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "Diminta oleh pihak sponsor untuk mem follow up kembali kesana 2 minggu lagi",
    "System (Imported)"
  ],
  [
    "SPN-066",
    "Game Blink",
    "-",
    "-",
    "-",
    "Rabu, 19 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-067",
    "Sumbar Smartphone",
    "-",
    "-",
    "-",
    "Rabu, 19 Agustus 2026",
    "-",
    "Ditinjau",
    "Pengajuan kerja sama sedang ditinjau oleh pihak sponsor.",
    "",
    "System (Imported)"
  ],
  [
    "SPN-068",
    "PT. Tazar Guna Mandiri",
    "-",
    "-",
    "-",
    "Kamis, 20 Agustus 2026",
    "-",
    "Ditolak",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-069",
    "PT Padang Distribusindo Raya ( Distributor Produk Wings Group )",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-070",
    "PT.Arena Agro Utama",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-071",
    "PT. ANUGRAH BUMINDO RESOURCES PADANG",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-072",
    "PT Multifiling Mitra Indonesia Tbk",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-073",
    "PT. Tigaraksa Satria, Tbk",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-074",
    "PT Yakult Indonesia Persada Cab. Padang",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-075",
    "PT. Kredo Keramindo Sejahtera",
    "-",
    "-",
    "-",
    "Kamis, 20 Agustus 2026",
    "-",
    "Ditinjau",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-076",
    "PT. Ekadharma International, Tbk Padang",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-077",
    "PT. MARI JAYA (Bypass)",
    "-",
    "-",
    "-",
    "Kamis, 20 Agustus 2026",
    "-",
    "Ditolak",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-078",
    "PT. Sinar Sosro",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-079",
    "PT. Natraco Spices Indonesia",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-080",
    "PT. Padang Raya Cakrawala",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "",
    "System (Imported)"
  ],
  [
    "SPN-081",
    "PT Indomex Dwijaya Lestari",
    "-",
    "-",
    "-",
    "-",
    "-",
    "Belum Dihubungi",
    "-",
    "-",
    "System (Imported)"
  ]
];
  
  if (seedData.length > 0) {
    sheet.getRange(2, 1, seedData.length, seedData[0].length).setValues(seedData);
    Logger.log("Sukses: " + seedData.length + " baris data Sponsor berhasil dimasukkan!");
  }
}